### ISSUE TITLE
There seems to be an unusual behavior in the assignment of player arenas.

### ISSUE THREAD

**Issue by AlHadiHabib** [tomkeuper/BWProxy2023#13]
When a player joins Arena 1 and subsequently another player joins the same group, the second player is erroneously being allocated to a different arena instead of Arena 1. Both arenas are intended to be part of the same group, yet the assignment seems to be inconsistent.

**Comment by tomkeuper** [comment]
This will only happen if the proxy plugin does not have any time to be updated. You can prevent this issue by turning off `random-selection` in the bwproxy config. 

It happens because when random selection is enabled the arena list is shuffled each time a player runs the `bw join` command. The arena cache will have no time to be properly updated. Adding code to prevent this issue will cause other problems and is thus not really an option. If you want to prevent this from happening turn off the random-selection option as described before.
